### ISSUE TITLE
Add AM - the Application Manager for GNU/Linux

### ISSUE THREAD

**Issue by sbstn87** [topgrade-rs/topgrade#206]
Hi,

is it possible to add AM - the Application Manager for GNU/Linux?

Link: https://github.com/ivan-hc/AM-Application-Manager

Short description: 
"AM" (ie "Application Manager") is a bash script able to install, update and remove thousands of standalone programs (any AppImage package, but also the official versions of Firefox, Thunderbird, Brave, Blender and hundreds of other programs provided on their official sites).

Install, update and manage AppImage packages and official standalone apps for GNU / Linux, with an ever-growing AUR-inspired database, scripts to manage AppImage builder tools and templates to create your own AppImages. Easy to use like APT and powerful like PacMan.

After installing the script, user has to type only: "sudo am -u" to update all packages installed via AM.

**Comment by epsimatic** [comment]
AM has just 45 Github stars, 2 forks, a single developer for 1000+ app-specific scripts, and it's written in bash. And I've never heard of it in the wild. 

Is it really that popular?

For OP: you can run any custom upgrade using custom `[commands]` section, like that:

```ini
[commands]
"AM" = "sudo am -u"
```

**Comment by sbstn87** [comment]
Thanks for your response.

To be honest, I do not know if it is popular. I use it and I think it is a great cross-distro package manager that works flawlessly for me. 

No idea how much work is it for you to add and maintain a new package manager. If it is burdensome, then perhaps it is better to wait for AM to get more traction in the community.

Otherwise I suppose that adding it may help it to get more recognition, as topgrade is a well-known app at the moment.

**Comment by epsimatic** [comment]
> I suppose that adding it may help it to get more recognition, as topgrade is a well-known app at the moment.

You see, leveraging a well-known app's feature to attract people to your favourite less-known app is a bad practice, and it's often scolded at or forbidden.

I'm not a Topgrade developer, though, so let them decide. Thumbs down from me (a random user) though

**Comment by DottoDev** [comment]
I do think it's worth adding it because topgrade should support as many package managers as possible and adding another package manager is always worth it.  Also it's not really difficult to implement it.

**Comment by christian-schulze** [comment]
@DottoDev  you didn't cover the case when `am` is not installed...

>sudo: am: command not found
>am failed: 
> 0: Command failed: `/bin/sudo am -u`
> 1: `/bin/sudo` failed: exit status: 1
>
>Location:
>   src/steps/os/linux.rs:440
>
>Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
>Run with RUST_BACKTRACE=full to include source snippets.
>Retry? (y)es/(N)o/(s)hell/(q)uit

**Comment by DottoDev** [comment]
I am officially stupid

**Comment by christian-schulze** [comment]
> I am officially stupid

Haha nah, we all push things hastily sometimes

**Comment by ivan-hc** [comment]
Hi, I'm the developer of AM Application Manager, thank you for your interest.

Here are something to know about it before you add it in Topgrade: https://github.com/topgrade-rs/topgrade/pull/328#issuecomment-1493498789

Just to be precise, @sbstn87 said:
> after installing the script, user has to type only: "sudo am -u" to update all packages installed via AM.

this is not correct, AM updates every app installed but without "sudo", you don't need to use it if not to install/remove the programs (all are installed in /opt with their dedicated directory, according to the Linux Standard Base).

@epsimatic said:

> AM has just 45 Github stars, 2 forks, a single developer for 1000+ app-specific scripts, and it's written in bash. And I've never heard of it in the wild.
>
> Is it really that popular?

No, it is not much popular. All I've done (in "marketing's" terms) was to post something on Reddit (r/AppImage, and r/linuxprojects), this repo was born in November 2021 and had never done the jump it was released for. This project was born for my use case first, then I have reworked to made it available for everybody as "[AM](https://github.com/ivan-hc/AM-Application-Manager)" (to install/remove everything in /opt as root, for all the users) or [AppMan](https://github.com/ivan-hc/AppMan)*** (everywhere in your $HOME directory, you choose where, no root privileges are needed indeed).

I've tried more to involve people interested in uploading installation scripts for AM using the option "-t" or "template", in this way everyone can create custom installation scripts for AM and everybody can join the project (it is released under GPL3), but after all this time I've not found anyone that can help me improve te repository. In my spare time (when it was enough) I've worked much on the x86_64 architecture (AM/AppMan can install/remove/manage apps for every architecture because it is just a bash script, this made it really universal), for now all the scripts managed for x86_64 are more than 1500, when I had the needing of more mainstream AppImage packages I've worked as a third-party packager so I've uploaded some unofficial AppImage packages for the more recent versions of GIMP, VLC, Chromium, MS Edge, Spotify... etcetera... the list of my repositories is on the main page of my github profile, at https://github.com/ivan-hc

I'm not a developer, I'm here just for fun, I do other things in my real life, far away from my passion for Linux and the informatics in general, and this is why my projects are not popular. I'm not here to be famous but to help those people with my same needings, and my need was an App Manager for standalone apps (maybe in AppImage format) always al the more recent version and that saves resources (disk space in particular) the more possible. However:

- I like Flatpak but I don't like all that runtimes installed, too much disk space spent (why not one runtime for all them?);
- I really love Docker/Podman/DistroBox instead, they are really better than Flatpak... I've also contributed to the Junest's project latelly, I really love them (the disk usage is less if compared with Flatpak, but still more if compared with other solutions, keep reading);
- I don't like Snaps, they are too slow;
- I like AppImages but they have not a software manager (I've done not one but two for them, in bash).

That said, I really hope that my solution is useful for someone else like it was for me. I've done it because I was bored (also the name I gave to the project is because I was bored... "AM", WTF is "AM"? XD).

#### *** NOTE: AppMan is the clone of AM, it converts the installation scripts for AM to installation scripts that can work without root privileges.
