### ISSUE TITLE
Error while self-updating

### ISSUE THREAD

**Issue by signorettae** [topgrade-rs/topgrade#338]
Hi, I was running topgrade 10.2.0 on my Ubuntu Server 22.04 istance and I got this error:
<pre>
―― 08:01:05 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Self update error: IoError: Permission denied (os error 13) at path "/usr/bin/topgrade_downloadYE2fJw"

</pre>

Here I report the ownership and permissions of the binary file

<pre>
-rwxr-xr-x  1 root root 12704528 Dec 18 15:45  topgrade

</pre>

I managed to solve it by manually downloading the new file and overwriting the old one

**Comment by DottoDev** [comment]
This is probably because topgrades is expects to be places in the home directory and because of that doesn't use sudo for runnign the update command. You could solve this problem by running topgrade with sudo privileges. If you want I could work on a fix for that but I don't think the effort will be worth the outcome.
