### ISSUE TITLE
Support for dnf5

### ISSUE THREAD

**Issue by mdhankins1** [topgrade-rs/topgrade#386]
## I want to suggest some general feature
Topgrade should support dnf5 on a host with Fedora 38 or higher if it is installed.

**Comment by msmafra** [comment]
ON Fedora 38 DNF5 is, for now, a MicroDNF upgrade and is on the route to be a DNF4¹ replacement, and is  not set nor installed as default yet and don't have all DNF4 (which still have its bin called dnf-3) features. It is expected³ to be the default on Fedora 39².
DNF5 already have _distro-sync_, _upgrade_, _upgrade-minimal_ working for the "daily" system update/upgrade with their differences as is on DNF4 where _distro-sync_ is more a conservative (for the lack of better word) upgrade method than _upgrade_.
In the case of DNF5 we are eager for it because DNF is painfully slow and DNF5 really made it better. Not yet at the speed of apt or pacman, for example, but took us away from the frustrating sloness.
I also would like to ask for it to be supported.

¹https://fedoraproject.org/wiki/Releases/38/ChangeSet#Major_upgrade_of_Microdnf
²https://fedoraproject.org/wiki/Releases/39/ChangeSet#Make_DNF5_The_Default
³https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5

**Comment by DottoDev** [comment]
> I also want this to be supported, but before the release of Fedora 39, `dnf5` will remain experimental, and, thus, is not recommended for daily package management.
> 
> The `dnf` in the current fedora is a symlink to `dnf-3`,
> 
> ```shell
> $ l $(which dnf)
> Permissions Links Size User Group Date Modified Name
> lrwxrwxrwx@     1    5 root root   6 Apr 16:40  /usr/bin/dnf -> dnf-3
> ```
> 
> and will be updated to point to `dnf5` in Fedora 39. From the [wiki](https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5#Upgrade/compatibility_impact), it should be compatible with the legacy `dnf-3` for most commands (I think [`dnf upgrade`](https://dnf5.readthedocs.io/en/latest/commands/upgrade.8.html) and [`dnf distro-sync`](https://dnf5.readthedocs.io/en/latest/commands/distro-sync.8.html) belong to them):
> 
> > Related `topgrade` code snippet: https://github.com/topgrade-rs/topgrade/blob/d640bc66f5861e72cb45d9bb9c69a984ba7fe21b/src/steps/os/linux.rs#L196C7-L202
> 
> > The DNF5 will provide some compatible aliases of commands and options to improve adoption of the DNF5
> 
> To summarize, to support `dnf5` before the release of Fedora 39, `topgrade` does need to add something new; To support it after the Fedora 39, `topgrade` needs to do nothing as interfaces will remain compatible.

Thanks for the writeup. `Topgrade` will not support `dnf5` while it is experimental. For everyone who does want to use it, you can run `dnf5` with a custom command and disable `dnf` in the config.

**Comment by nivaca** [comment]
> For everyone who does want to use it, you can run dnf5 with a custom command and disable dnf in the config.

How can I do that? I'm using dnf5 without any problems and want to incorporate it in the topgrade process.

**Comment by SteveLauC** [comment]
> How can I do that? I'm using dnf5 without any problems and want to incorporate it in the topgrade process.

Fedora 39 does not make dnf5 the default dnf, if you opt in to use it as your daily package manager, I think you can remove the old `dnf` command and rename `dnf5` to `dnf`


If you want to use both dnf4 and dnf5, you have to write your own custom commands to update with dnf5:

```toml
[misc]
disable = ["system"] # disable the built-in step that uses `dnf4`

[commands]
dnf5 = "sudo dnf5 update" # your custom step to update the system with `dnf5`
```

**Comment by nivaca** [comment]
Many thanks.
