### ISSUE TITLE
Support `homebrew-bundle` to keep `brew`s up-to-date

### ISSUE THREAD

**Issue by paddyroddy** [topgrade-rs/topgrade#601]
### Which tool is this about? Where is its repository?
A tool which keeps local `brew` packages up-to-date https://github.com/Homebrew/homebrew-bundle, allows you to track your `brew`s in a dotfile
### Which operating systems are supported by this tool?
`macOS` & `Linux`
### What should Topgrade do to figure out if the tool needs to be invoked?
Check to see if any new `brew`s have been installed
### Which exact commands should Topgrade run?
`bundle dump --describe --force --file <filename>`

**Comment by SteveLauC** [comment]
Mind submitting a PR? you can see CONTRIBUTING.md on how to add a new step

**Comment by paddyroddy** [comment]
I've thought about it a bit and wondered if this is something you'd want. It's not a strict upgrade, but more keeping a file in sync. Is that something you'd want?

**Comment by SteveLauC** [comment]
> It's not a strict upgrade, but more keeping a file in sync. Is that something you'd want?

I am not a `brew` user, so not familiar with these `brew` terms, but it seems to be a nice step to have

> Which exact commands should Topgrade run?
>
> bundle dump --describe --force --file filename

So that `<filename>` argument needs to be manually specified by the user, if so, then we need to add a configuration entry for it under the `[brew]` section:

https://github.com/topgrade-rs/topgrade/blob/465df2e9bea2150b11ea63248198918225784629/config.example.toml#L105-L107

> What should Topgrade do to figure out if the tool needs to be invoked?

We need to check:

1. `brew` is installed
2. the configuration entry is provided in the configuration file (every configuration entry should be `Option`al)
    
    > if this entry is not provided, we should [skip](https://github.com/topgrade-rs/topgrade/blob/465df2e9bea2150b11ea63248198918225784629/src/steps/generic.rs#L41) this step

Then we run this step


------

Feel free to ping me when you get trouble while implementing this feature:)

**Comment by paddyroddy** [comment]
Okay cheers, will have a look

**Comment by paddyroddy** [comment]
I've realised that there is quite a lot to modify for my case - I don't like the standard output. So I'm going to close this as others may have similar thoughts https://github.com/paddyroddy/dotfiles/blob/e4f34acf31258025c9ad7319eb94f20509b4863f/.config/homebrew/update.sh%23%23os.Darwin#L1-L25.
