### ISSUE TITLE
Support for `xcodes`

### ISSUE THREAD

**Issue by schrobingus** [topgrade-rs/topgrade#630]
### Which tool is this about? Where is its repository?
A tool that manages Xcode versions, which can be found [here](https://github.com/XcodesOrg/xcodes). 

I can work on this, just wanted to discuss prior to make sure this can be implemented without any possible glaring issues, since this tool installs individual Xcode versions as opposed to upgrading at once.

### Which operating systems are supported by this tool?
macOS only.

### What should Topgrade do to figure out if the tool needs to be invoked?
It should install the latest version, in correlation to if the user is running a stable, beta, or golden master release. Since this wouldn't be removing the old version automatically, it might be best to prompt the user before invoking (like with macOS system updates).

### Which exact commands should Topgrade run?
`xcodes update`
`xcodes list`
(sort output to find installed and latest, detect the keywords Beta and GM and mind them when finding the latest version)
`xcodes install (release)`

**Comment by SteveLauC** [comment]
Hi, this sounds like a nice step to add, I have some questions:

1. For macOS/iOS developers, what will be included in an Xcode update if there is no macOS major version bump?

    > If there is a macOS update, IIRC, there will be a new SDK available.

2. Does `xcodes install (release)` need a confirmation? i.e., users need to input `yes/y` to approve the installation.
3. Does this command support the `--dry-run` option, i.e., show users what will be done without actually doing it.
4. Since this tool itself is not an Xcode updater but a manager, should we inform (print to stdout) users of what will be done?

**Comment by BrentBoyMeBob** [comment]
1. You'd be correct that there are new SDKs. When it comes to minor updates:
    - Standard releases generally include bug fixes and sometimes minor feature additions.
    - Beta releases sometimes include the features initially announced. Other times, they will be added gradually through development in large stages (for example, the VisionOS toolkit and simulator). A lot heavier on bugs and their fixes here as well.
2. Not sure, I will test right now and return the results.
3. I don't think there is a dry run option bundled in if I remember correctly.
4. Absolutely, as for example, Xcode is large in terms of file size, and the old version won't be getting removed, so there should definitely be a brief overview of what will be run.

**Comment by SteveLauC** [comment]
> 2. Does xcodes install (release) need a confirmation? i.e., users need to input yes/y to approve the installation.


> Not within the command, no, but there are some imperative prompts.

Besides that Apple ID confirmation, we can explicitly ask users if they want to update when detecting new releases (xcodes list) before we actually do it with `xcodes install xxx`.

It won't be something like this:

```sh
$ topgrade --only xcodes

── 09:04:56 - Xcodes ─────────────────────────────────────────────────────────────
New Xcode release detected: 
x.x.x
x.x.x

Install them? (y)es/(N)o
```

If users pass the `--yes` option or the corresponding entry in the configuration file, then we can directly do the installaction:

```sh
$ topgrade --only xcodes --yes

── 09:04:56 - Xcodes ─────────────────────────────────────────────────────────────
New Xcode release detected: x.x.x

Installing x.x.x...
```

And I think this can get the following task done:

> 4. Since this tool itself is not an Xcode updater but a manager, should we inform (print to stdout) users of what will be done?

------

Since `xcodes` itself does not support the `--dry-run` option, we need to emulate it, when detecting this option, simply print what will be done:

```sh
$ topgrade --only xcodes --dry-run
Dry running: xcodes update
Dry running: xcodes list
Dry running: xcodes install new-releases
```

> Topgrade has a dry-run layer itself, but it is not suitable for a step that needs to execute multiple commands and has the commands relying on each other.

**Comment by schrobingus** [comment]
Sounds good, I'll submit a pull request for this.

**Comment by SteveLauC** [comment]
Close as completed in #643
