### ISSUE TITLE
topgrade v13.0.0 Z4H SSH issue

### ISSUE THREAD

**Issue by lbonvarl** [topgrade-rs/topgrade#646]
I am using [topgrade](https://github.com/topgrade-rs/topgrade) on an ARM64 Debian 12 VM via SSH, where Z4H is configured in shell. It seems similar to some issues experienced with other zsh configs:
https://github.com/r-darwish/topgrade/issues/380
https://github.com/r-darwish/topgrade/issues/394
```
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Step "antibody"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Step "antidote"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Step "antigen"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/loic/.zshrc" exists
DEBUG Step "zgenom"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/loic/.zshrc" exists
DEBUG Step "zplug"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/loic/.zshrc" exists
DEBUG Step "zinit"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/loic/.zshrc" exists
DEBUG Step "zi"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/loic/.zshrc" exists
DEBUG Step "zim"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Executing command `zsh -c '[[ -n ${ZIM_HOME} ]] && print -n ${ZIM_HOME}'`
DEBUG Command failed: Err(
   0: Command failed: `zsh -c '[[ -n ${ZIM_HOME} ]] && print -n ${ZIM_HOME}'`
   1: `zsh` failed: exit status: 1

Location:
   /home/loic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/zsh.rs:151)
DEBUG Step "oh-my-zsh"
DEBUG Detected "/usr/bin/zsh" as "zsh"
DEBUG Path "/home/loic/.zshrc" exists
DEBUG Executing command `zsh -c 'source /home/loic/.zshrc > /dev/null && export -p | grep ZSH > /dev/null && echo $ZSH'`
DEBUG Command failed: Err(
   0: Command failed: `zsh -c 'source /home/loic/.zshrc > /dev/null && export -p | grep ZSH > /dev/null && echo $ZSH'`

      Stderr:
      /home/loic/.zshrc:56: command not found: z4h
   1: `zsh` failed: exit status: 127

Location:
   /home/loic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/zsh.rs:190)
DEBUG Step "oh-my-zsh" failed:
   0: Command failed: `zsh -c 'source /home/loic/.zshrc > /dev/null && export -p | grep ZSH > /dev/null && echo $ZSH'`

      Stderr:
      /home/loic/.zshrc:56: command not found: z4h
   1: `zsh` failed: exit status: 127

Location:
   /home/loic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/zsh.rs:190
oh-my-zsh failed:
   0: Command failed: `zsh -c 'source /home/loic/.zshrc > /dev/null && export -p | grep ZSH > /dev/null && echo $ZSH'`

      Stderr:
      /home/loic/.zshrc:56: command not found: z4h
   1: `zsh` failed: exit status: 127

Location:
   /home/loic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/zsh.rs:190
Retry? (y)es/(N)o/(s)hell/(q)uit
```

See answer from https://github.com/romkatv/zsh4humans/issues/287

              If I understand it correctly, this code is running the following command:

```zsh
zsh -c 'source /home/loic/.zshrc > /dev/null && export -p | grep ZSH > /dev/null && echo $ZSH'
```

This command is not supposed to work, so sometimes it does not. Try this instead:

```zsh
zsh -ic 'print -r -- ${ZSH:?}'
```

This is the whole command that you can use as a substitute for the buggy one.

_Originally posted by @romkatv in https://github.com/romkatv/zsh4humans/issues/287#issuecomment-1900930694_

**Comment by SteveLauC** [comment]
Have you tried the script given by the author of the z4g? Does it work?

**Comment by lbonvarl** [comment]
The command does work correctly:
```
zsh -c 'source /home/loic/.zshrc > /dev/null && export -p | grep ZSH > /dev/null && echo $ZSH'                                                                          
/home/loic/.zshrc:56: command not found: z4h

zsh -ic 'print -r -- ${ZSH:?}'                                                                                                                                          
/home/loic/.cache/zsh4humans/v5/ohmyzsh/ohmyzsh
```

**Comment by lbonvarl** [comment]
Thanks @romkatv for your comments and directions.

**Comment by SteveLauC** [comment]
> Note that the first command is broken not just for z4h but for zsh general. 

Thanks for your help @romkatv, would you like to explain a bit about why the script that is in use is not correct? I am not that familiar with shell scripting, so kinda curious:D

**Comment by romkatv** [comment]
The script is sourcing `.zshrc`. This action has unpredictable consequences and should never be done.

Then there is `export -p | grep ZSH` which, I believe, is meant to check whether `ZSH` is exported but in practice it checks for something else. For example, this command will succeed if `PATH` contains a directory with "ZSH" in its name. Moreover, it's entirely normal for zsh users to define `ZSH` and not export it.

Lastly, there is a bug in the `echo` command but in practice it's unlikely to matter. You can see the effect of this bug if you set `ZSH` to `/\n` or to `-n`.

My command fixes all these issues. It prints `$ZSH` if `ZSH` is defined and not empty. Otherwise it fails.

**Comment by SteveLauC** [comment]
> The script is sourcing .zshrc. This action has unpredictable consequences and should never be done.

Do you mean that a zsh process should ONLY source its rc file once, otherwise, UB can happen?

**Comment by romkatv** [comment]
That is correct. Zsh guarantees the list of files that get sourced on startup and the order of sourcing them. Sourcing zsh startup files in the wrong order, or more than once, or the wrong ones (e.g., sourcing `.zshrc` in a non-interactive shell) will have unpredictable results because in general users rely on the guarantees.

Here's an analogy. When you write a function in Rust, you enjoy a guarantee that the lines in the function will be executed in a very specific order, and, for example, the line after `if false` won't be executed. If a tool starts executing your code without providing the same guarantee, the outcome will be unpredictable. Zsh startup files contain code, too.

**Comment by SteveLauC** [comment]
Thanks! Today I learned! Thanks for your help on this issue!

**Comment by romkatv** [comment]
Sure thing.

It's not uncommon to see `source ~/.zshrc` used by beginners to apply modifications to `.zshrc` without restarting the terminal. There is a much better alternative: `exec zsh`. Not only it avoids a multitude of issues that `source ~/.zshrc` can bring, it's also easier to type.

**Comment by SteveLauC** [comment]
Yeah, I guess I will no longer use that source command when applying changes:>
